{"uuid": "5bb524e5-791b-49b5-9bd2-8cda9c858acf", "children": ["527e14cd-b5bb-4766-8a74-fdfb525d1e98", "8e351468-beb2-4505-8a0d-43a3e235cedc", "de4169cd-849f-4bd5-ab46-3ef76defd04a", "3456cb82-3cf7-4c08-b1dd-3d79bbc2054d"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/tests/conftest.py\", line 37, in driver\n    options.load_capabilities(android_get_desired_capabilities())\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/utils/android_utils.py\", line 22, in android_get_desired_capabilities\n    'udid': udid[0],\n            ~~~~^^^\n"}, "start": 1730748174684, "stop": 1730748174694}], "start": 1730748174684, "stop": 1730748174720}