{"uuid": "cccefc5b-3671-4546-8343-2b0385426b73", "children": ["5c75da8a-ac17-4f78-8035-ae33912f9e62", "6d1d44e0-2cc5-40de-9d14-77db850a79fb", "4f8f2659-1b30-4b9d-b2d7-1a56feb33b2b"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/tests/conftest.py\", line 37, in driver\n    options.load_capabilities(android_get_desired_capabilities())\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/ilonapetenko/Documents/test_task-main/utils/android_utils.py\", line 22, in android_get_desired_capabilities\n    'udid': udid[0],\n            ~~~~^^^\n"}, "start": 1730748114079, "stop": 1730748114088}], "start": 1730748114079, "stop": 1730748114093}